# GNU Make project makefile autogenerated by Premake
ifndef config
	config=release
endif

ifndef verbose
	SILENT = @
endif

ifndef sailfish_arch
	sailfish_arch=armv7hl
endif

CC = gcc
CXX = g++
AR = ar

ifndef RESCOMP
	ifdef WINDRES
		RESCOMP = $(WINDRES)
	else
		RESCOMP = windres
	endif
endif

ifeq ($(sailfish_arch),armv7hl)
	BASEDIR	 = ../../../Output/Targets/SailfishOS-32
else
	ifeq ($(sailfish_arch),aarch64)
		BASEDIR	 = ../../../Output/Targets/SailfishOS-64
	else
		BASEDIR	 = ../../../Output/Targets/SailfishOS-32-x86
	endif
endif

ifeq ($(config),release)
	OBJDIR		 = $(BASEDIR)/Release/obj/vorbis
	TARGETDIR	 = $(BASEDIR)/Release/lib
	TARGET		 = $(TARGETDIR)/libvorbis.a
	DEFINES	        += -Dalloca=__builtin_alloca
	INCLUDES	    += -I../../../../../vorbis/include -I../../../../../vorbis/lib
	ALL_CPPFLAGS	+= $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
	ALL_CFLAGS		+= $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -ffast-math -Wall -Wextra -O2 -std=c99 -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-switch -Wno-missing-field-initializers -fPIC -fvisibility=hidden
	ALL_CXXFLAGS	+= $(CXXFLAGS) $(ALL_CFLAGS)
	ALL_RESFLAGS	+= $(RESFLAGS) $(DEFINES) $(INCLUDES)
	ALL_LDFLAGS	  += $(LDFLAGS) -L$(BASEDIR)/Release/lib -s
	LDDEPS		+=
	LIBS			+= $(LDDEPS)
	LINKCMD		= $(AR) -rcs $(TARGET) $(OBJECTS)
endif

ifeq ($(config),debug)
	OBJDIR		 = $(BASEDIR)/Debug/obj/vorbis
	TARGETDIR	 = $(BASEDIR)/Debug/lib
	TARGET		 = $(TARGETDIR)/libvorbis.a
	DEFINES	        += -Dalloca=__builtin_alloca
	INCLUDES	    += -I../../../../../vorbis/include -I../../../../../vorbis/lib
	ALL_CPPFLAGS	+= $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
	ALL_CFLAGS		+= $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -ffast-math -Wall -Wextra -g -std=c99 -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-switch -Wno-missing-field-initializers -fPIC -fvisibility=hidden
	ALL_CXXFLAGS	+= $(CXXFLAGS) $(ALL_CFLAGS)
	ALL_RESFLAGS	+= $(RESFLAGS) $(DEFINES) $(INCLUDES)
	ALL_LDFLAGS	  += $(LDFLAGS) -L$(BASEDIR)/Debug/lib
	LDDEPS		+=
	LIBS			+= $(LDDEPS)
	LINKCMD		= $(AR) -rcs $(TARGET) $(OBJECTS)
endif

OBJECTS := \
	$(OBJDIR)/bitrate.o \
	$(OBJDIR)/misc.o \
	$(OBJDIR)/mdct.o \
	$(OBJDIR)/lookup.o \
	$(OBJDIR)/info.o \
	$(OBJDIR)/lpc.o \
	$(OBJDIR)/envelope.o \
	$(OBJDIR)/lsp.o \
	$(OBJDIR)/codebook.o \
	$(OBJDIR)/vorbisfile.o \
	$(OBJDIR)/window.o \
	$(OBJDIR)/psy.o \
	$(OBJDIR)/registry.o \
	$(OBJDIR)/res0.o \
	$(OBJDIR)/vorbisenc.o \
	$(OBJDIR)/barkmel.o \
	$(OBJDIR)/synthesis.o \
	$(OBJDIR)/analysis.o \
	$(OBJDIR)/sharedbook.o \
	$(OBJDIR)/floor1.o \
	$(OBJDIR)/block.o \
	$(OBJDIR)/mapping0.o \
	$(OBJDIR)/smallft.o \
	$(OBJDIR)/floor0.o \


RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
	SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
	SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking vorbis
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning vorbis
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f	$(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -MMD -MP $(DEFINES) $(INCLUDES) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/bitrate.o: ../../../../../vorbis/lib/bitrate.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/misc.o: ../../../../../vorbis/lib/misc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/mdct.o: ../../../../../vorbis/lib/mdct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/lookup.o: ../../../../../vorbis/lib/lookup.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/info.o: ../../../../../vorbis/lib/info.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/lpc.o: ../../../../../vorbis/lib/lpc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/envelope.o: ../../../../../vorbis/lib/envelope.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/lsp.o: ../../../../../vorbis/lib/lsp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/codebook.o: ../../../../../vorbis/lib/codebook.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/vorbisfile.o: ../../../../../vorbis/lib/vorbisfile.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/window.o: ../../../../../vorbis/lib/window.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/psy.o: ../../../../../vorbis/lib/psy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/registry.o: ../../../../../vorbis/lib/registry.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/res0.o: ../../../../../vorbis/lib/res0.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/vorbisenc.o: ../../../../../vorbis/lib/vorbisenc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/barkmel.o: ../../../../../vorbis/lib/barkmel.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/synthesis.o: ../../../../../vorbis/lib/synthesis.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/analysis.o: ../../../../../vorbis/lib/analysis.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/sharedbook.o: ../../../../../vorbis/lib/sharedbook.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/floor1.o: ../../../../../vorbis/lib/floor1.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/block.o: ../../../../../vorbis/lib/block.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/mapping0.o: ../../../../../vorbis/lib/mapping0.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/smallft.o: ../../../../../vorbis/lib/smallft.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/floor0.o: ../../../../../vorbis/lib/floor0.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"
	

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
	-include $(OBJDIR)/$(notdir $(PCH)).d
endif
